// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvdgjlhucllfexdiwekh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZGdqbGh1Y2xsZmV4ZGl3ZWtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDk1MjksImV4cCI6MjA2MDY4NTUyOX0.1bsFmfAeu50B_fe-BAGNbQwj93SNrgiwy5tzY9DYzmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);